#    邮箱配置
spring:
  mail:
    host: smtp.qq.com
    username: 2998180835@qq.com
    password: cutlceogvvpgdhdj
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
