server:
  port: 8003
spring:
  application:
    name: com.youxin.excel
  datasource:
    url: jdbc:mysql://localhost:3307/gu_li?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root